#!/usr/bin/env bash

# List of files to commit.
files=(
	"main"
	"kanashi/__init__.py"
	"kanashi/cli/__init__.py"
	"kanashi/enpoint/__init__.py"
	"kanashi/enpoint/profile.py"
	"kanashi/enpoint/user.py"
	"kanashi/utils/__init__.py"
	"kanashi/utils/file.py"
	"kanashi/utils/json.py"
	"kanashi/utils/path.py"
	"kanashi/utils/string.py"
	"kanashi/utils/thread.py"
	"kanashi/utils/util.py"
	"kanashi/config.py"
	"kanashi/context.py"
	"kanashi/error.py"
	"kanashi/kanashi.py"
	"kanashi/object.py"
	"kanashi/request.py"
	"kanashi/signin.py"
)

#[upper String]
function upper()
{
	# Convert string character to Upper case.
	echo $1 | tr \"[:lower:]\" \"[:upper:]\"
}

# Clear terminal screen
clear

# Github authentication token
echo -e "Token \x1b[1;32m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\x1b[0m"
echo -e

# User interaction
echo -e "Update one by one or all [Y/n] \c"
read single

# If single mode is True
if [[ $( upper $single ) == "Y" ]]; then
	
	# Mapping files
	for file in "${files[@]}"; do
		
		# Clear terminal screen
		clear
		
		# User interaction
		echo -e "Push file \x1b[1;38;5;111m$file\x1b[0m [Y/n] \c"
		read push
		
		# If file is pushable
		if [[ $( upper $push ) == "Y" ]]; then
			
			echo -e "git add $file"
			echo -e "git commit -m default=Update"
			echo -e "git commit -m \c"
			read commit
			
			if [[ $commit == "" ]]; then
				$commit="Update"
			fi
			
			git add $file
			git commit -m "\"$commit\""
			git push
			
		fi
	done
else
	
	# Join array element into string
	file=$( echo "${files[*]}" )
	
	echo -e "git add $file"
	echo -e "git commit -m default=Update"
	echo -e "git commit -m \c"
	read commit
	
	if [[ $commit == "" ]]; then
		$commit="Update"
	fi
	
	git add $file
	git commit -m "\"$commit\""
	git push
fi